const themesList = {
  ambiance: 'Ambiance',
  chaos: 'Chaos',
  chrome: 'Chrome',
  clouds: 'Clouds',
  clouds_midnight: 'Clouds (Midnight)',
  cobalt: 'Cobalt',
  dawn: 'Dawn',
  eclipse: 'Eclipse',
  github: 'GitHub',
  idle_fingers: 'IDLE Fingers',
  iplastic: 'iPlastic',
  kuroir: 'Kuroir',
  merbivore: 'Merbivore',
  merbivore_soft: 'Merbivore (Soft)',
  mono_industrial: 'Mono Industrial',
  monokai: 'Monokai',
  pastel_on_dark: 'Pastel On Dark',
  solarized_dark: 'Solarized (Dark)',
  solarized_light: 'Solarized (Light)',
  terminal: 'Terminal',
  textmate: 'TextMate',
  tomorrow: 'Tomorrow',
  tomorrow_night: 'Tomorrow (Night)',
  twilight: 'Twilight',
  xcode: 'XCode',
};
